const tasks=[
 {id:'2D-20260910-00128',name:'简约木质书架',note:'优先处理主视角素材',stage:'批量上传原图',status:'上传中',type:'running',progress:8,target:42,meta:'上传中 12 / 42',owner:'王岩',time:'今天 10:58'},
 {id:'2D-20260910-00127',name:'现代玻璃花瓶',note:'保留透明材质细节',stage:'AI 初筛',status:'排队中',type:'neutral',progress:18,target:30,meta:'上传 46 · 等待 AI 初筛',owner:'陈建模',time:'今天 10:49'},
 {id:'2D-20260910-00126',name:'人体工学办公椅',note:'用于办公场景资产',stage:'原图复核',status:'待人工复核',type:'action',progress:52,target:50,meta:'初筛完成 92 · 待复核 92',owner:'陈建模',time:'今天 10:42'},
 {id:'2D-20260910-00125',name:'北欧落地灯',note:'优先保留灯罩结构',stage:'AI 初筛',status:'处理中',type:'running',progress:22,target:40,meta:'上传 80 · 初筛 18 · 失败 1',owner:'林嘉',time:'今天 10:31'},
 {id:'2D-20260910-00124',name:'复古皮质行李箱',note:'突出皮质纹理',stage:'AI 图生图',status:'处理中',type:'running',progress:62,target:30,meta:'输入 46 · 图生图处理中',owner:'陈建模',time:'今天 09:58'},
 {id:'2D-20260910-00123',name:'工业金属工具柜',note:'需检查边缘完整性',stage:'成图质检',status:'待人工质检',type:'action',progress:78,target:36,meta:'生成 42 · 待质检 42 · 已通过 0',owner:'王岩',time:'今天 09:20'},
 {id:'2D-20260909-00122',name:'原木圆形餐桌',note:'餐桌素材补充批次',stage:'2D 入库',status:'处理中',type:'running',progress:91,target:45,meta:'质检通过 47 · 入库 40 · 失败 2',owner:'陈建模',time:'昨天 18:46'},
 {id:'2D-20260909-00119',name:'陶瓷花瓶',note:'',stage:'已完成',status:'已完成',type:'done',progress:100,target:50,meta:'上传 102 · 质检通过 53 · 入库 53',owner:'林嘉',time:'昨天 16:18'},
 {id:'2D-20260908-00112',name:'儿童学习桌',note:'优先输出主视角',stage:'AI 图生图',status:'生成失败',type:'exception',progress:56,target:60,meta:'输入 72 · 模型服务暂不可用，请重试',owner:'王岩',time:'09-08 17:26'}
];
const submittedImageToImageTask=new URLSearchParams(location.search).get('i2iSubmitted');
if(submittedImageToImageTask){const task=tasks.find(item=>item.id===submittedImageToImageTask);if(task){const count=Number(new URLSearchParams(location.search).get('count'))||0;task.stage='AI 图生图';task.status='排队中';task.type='neutral';task.progress=60;task.meta=`输入 ${count} · 等待图生图处理`;task.time='刚刚';setTimeout(()=>{task.status='处理中';task.type='running';task.progress=68;task.meta=`输入 ${count} · 图生图处理中`;syncStatusOptions();render()},1200);setTimeout(()=>{task.stage='成图质检';task.status='待人工质检';task.type='action';task.progress=78;task.meta=`生成成功 ${count} · 待质检 ${count}`;syncStatusOptions();render()},2400)}history.replaceState({},'',location.pathname)}
const body=document.querySelector('#taskBody'),empty=document.querySelector('#emptyState'),count=document.querySelector('#resultCount');
let view='all';
const stageFilter=document.querySelector('#stageFilter'),statusFilter=document.querySelector('#statusFilter'),ownerFilter=document.querySelector('#ownerFilter');
const listTimeFilter=document.querySelector('#listTimeFilter'),statsModal=document.querySelector('#statsModal'),statsPeriodFilter=document.querySelector('#statsPeriodFilter'),statsCustomRange=document.querySelector('#statsCustomRange'),statsPeriodStart=document.querySelector('#statsPeriodStart'),statsPeriodEnd=document.querySelector('#statsPeriodEnd');
const statisticToday=new Date(2026,8,10);
function taskCreatedDate(task){const match=task.id.match(/2D-(\d{4})(\d{2})(\d{2})/);return match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3])):statisticToday}
function atStart(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate())}
function periodRange(period,startValue='',endValue=''){const today=atStart(statisticToday);if(period==='all')return[new Date(2026,0,1),today];if(period==='today')return[today,today];if(period==='yesterday'){const d=new Date(today);d.setDate(d.getDate()-1);return[d,d]}if(period==='seven'){const d=new Date(today);d.setDate(d.getDate()-6);return[d,today]}if(period==='this-week'){const d=new Date(today);d.setDate(d.getDate()-((d.getDay()+6)%7));return[d,today]}if(period==='last-week'){const end=new Date(today);end.setDate(end.getDate()-((end.getDay()+6)%7)-1);const start=new Date(end);start.setDate(start.getDate()-6);return[start,end]}if(period==='month')return[new Date(today.getFullYear(),today.getMonth(),1),today];if(period==='custom'&&startValue&&endValue)return[atStart(new Date(`${startValue}T00:00:00`)),atStart(new Date(`${endValue}T00:00:00`))];return[today,today]}
function tasksInPeriod(period,startValue='',endValue=''){const[start,end]=periodRange(period,startValue,endValue);return tasks.filter(task=>{const date=taskCreatedDate(task);return date>=start&&date<=end})}
function calculateStatistics(periodTasks){const state={processing:0,pending:0,exception:0};periodTasks.forEach(task=>{if(task.type==='action')state.pending++;else if(task.type==='exception')state.exception++;else if(task.type==='running'||task.type==='neutral')state.processing++});const totals=periodTasks.reduce((result,task)=>{const uploaded=task.target||Math.max(20,Math.round(task.progress*.8));result.uploaded+=uploaded;result.screened+=Math.round(uploaded*.84);result.processed+=Math.round(uploaded*.67);result.passed+=Math.round(uploaded*.52);result.inbound+=Math.round(uploaded*.5);result.threeD+=Math.round(uploaded*.18);result.minutes+=48+Math.round(task.progress*2.2);return result},{uploaded:0,screened:0,processed:0,passed:0,inbound:0,threeD:0,minutes:0});return{state,totals,average:periodTasks.length?Math.round(totals.minutes/periodTasks.length):0}}
function updateListSummary(periodTasks){const stats=calculateStatistics(periodTasks);document.querySelector('#summaryAll').textContent=periodTasks.length;document.querySelector('#summaryProcessing').textContent=stats.state.processing;document.querySelector('#summaryPending').textContent=stats.state.pending;document.querySelector('#summaryException').textContent=stats.state.exception}
function updateStatsModal(){const periodTasks=tasksInPeriod(statsPeriodFilter.value,statsPeriodStart.value,statsPeriodEnd.value),stats=calculateStatistics(periodTasks),duration=stats.average>=60?`${Math.floor(stats.average/60)} 小时 ${stats.average%60} 分`:`${stats.average} 分钟`;document.querySelector('#statsAll').textContent=periodTasks.length;document.querySelector('#statsProcessing').textContent=stats.state.processing;document.querySelector('#statsPending').textContent=stats.state.pending;document.querySelector('#statsException').textContent=stats.state.exception;document.querySelector('#statsUploaded').textContent=`${stats.totals.uploaded} 张`;document.querySelector('#statsScreened').textContent=`${stats.totals.screened} 张`;document.querySelector('#statsProcessed').textContent=`${stats.totals.processed} 张`;document.querySelector('#statsPassed').textContent=`${stats.totals.passed} 张`;document.querySelector('#statsInbound').textContent=`${stats.totals.inbound} 张`;document.querySelector('#stats3d').textContent=`${stats.totals.threeD} 张`;document.querySelector('#statsDuration').textContent=`平均全流程耗时：${duration}`}
const stageStatusOptions={
  '批量上传原图':['上传中','上传完成','上传失败','校验失败'],
  'AI 初筛':['排队中','处理中','初筛完成，待原图复核','初筛部分失败','初筛失败'],
  '原图复核':['待人工复核','复核完成，待图生图配置','无通过图片，任务结束'],
  'AI 图生图':['待提交配置','排队中','处理中','生成成功，待成图质检','生成失败'],
  '成图质检':['待人工质检','质检完成，待入库','无合格成图，任务结束'],
  '分类/标签/命名':['待补全信息','信息校验失败','待入库'],
  '2D 入库':['入库中','已入库','入库失败'],
  '已完成':['已完成']
};
function syncStatusOptions(){const selectedStage=stageFilter.value,previous=statusFilter.value,statuses=selectedStage==='all'?[...new Set(Object.values(stageStatusOptions).flat())]:stageStatusOptions[selectedStage]||[];statusFilter.innerHTML=`<option value="all">全部当前状态</option>${statuses.map(status=>`<option value="${status}">${status}</option>`).join('')}`;statusFilter.value=statuses.includes(previous)?previous:'all'}
function render(){const q=document.querySelector('#searchInput').value.trim().toLowerCase(),status=statusFilter.value,stage=stageFilter.value,owner=ownerFilter.value,sort=document.querySelector('#sortFilter').value,periodTasks=tasksInPeriod(listTimeFilter.value);updateListSummary(periodTasks);const rows=periodTasks.filter(t=>(!q||t.id.toLowerCase().includes(q)||t.name.toLowerCase().includes(q))&&(status==='all'||t.status===status)&&(stage==='all'||t.stage===stage)&&(owner==='all'||t.owner===owner)&&(view==='all'||t.owner==='陈建模')).sort((a,b)=>{const id=(task)=>Number(task.id.replace(/\D/g,''));if(sort==='progress-desc')return b.progress-a.progress;if(sort==='progress-asc')return a.progress-b.progress;if(sort==='time-asc')return id(a)-id(b);return id(b)-id(a)});body.innerHTML=rows.map(t=>{const reviewAction=t.status==='待人工复核'?`<a class="action-link" href="quality.html?tab=source&task=${t.id}">开始复核</a>`:t.status==='待人工质检'?`<a class="action-link" href="quality.html?tab=generated&task=${t.id}">开始质检</a>`:'';return `<tr data-id="${t.id}"><td><div class="task-cell"><div class="task-name"><strong>${t.name}</strong><code>${t.id}</code></div></div></td><td><span class="stage"><i class="stage-dot"></i>${t.stage}</span></td><td><span class="status ${t.type}">${t.status}</span></td><td><div class="progress"><div class="progress-top"><strong>${t.meta}</strong><span>${t.progress}%</span></div><div class="progress-bar"><i style="width:${t.progress}%"></i></div></div></td><td><div class="owner"><span class="mini-avatar">${t.owner[0]}</span>${t.owner}</div></td><td><span class="time">${t.time}</span></td><td><span class="task-note" title="${t.note||''}">${t.note||'—'}</span></td><td><button class="action-link" data-details>详情</button>${reviewAction}</td></tr>`}).join('');empty.classList.toggle('show',rows.length===0);count.textContent=`共 ${rows.length} 条`;body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>openDrawer(tasks.find(t=>t.id===row.dataset.id))));}
function reset(){document.querySelector('#searchInput').value='';stageFilter.value='all';ownerFilter.value='all';document.querySelector('#sortFilter').value='time-desc';syncStatusOptions();render()}
document.querySelector('#searchInput').addEventListener('input',render);statusFilter.addEventListener('change',render);stageFilter.addEventListener('change',()=>{syncStatusOptions();render()});ownerFilter.addEventListener('change',render);document.querySelector('#sortFilter').addEventListener('change',render);document.querySelector('#resetBtn').addEventListener('click',reset);document.querySelector('#emptyReset').addEventListener('click',reset);
document.querySelectorAll('.view-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.view-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');view=btn.dataset.view;render()}));
const drawer=document.querySelector('#taskDrawer'),overlay=document.querySelector('#drawerOverlay');
function formatTaskStageTime(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')} ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
function addTaskMinutes(date,minutes){return new Date(date.getTime()+minutes*60000)}
function buildTaskTimeline(t){const match=t.id.match(/2D-(\d{4})(\d{2})(\d{2})/),base=match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),9,20):new Date(2026,8,10,9,20),steps=[{key:'批量上传原图',label:'批量上传原图',desc:'原图已接入并生成 Image Item ID',minutes:8},{key:'AI 初筛',label:'AI 初筛',desc:'自动筛选候选原图',minutes:18},{key:'原图复核',label:'图片处理复核',desc:'建模师决定编辑图、图生图或不通过',minutes:29},{key:'AI 图生图',label:'AI 图片处理',desc:'编辑图与图生图均按 N 进 N 出处理',minutes:13},{key:'成图质检',label:'成图质检',desc:'人工质检候选成图',minutes:17},{key:'2D 入库',label:'2D 入库',desc:'创建正式 2D Asset',minutes:7},{key:'已完成',label:'发起 3D',desc:'正式 2D Asset 可加入 3D 批次任务',minutes:0}];const stageIndex=Math.max(0,steps.findIndex(step=>step.key===t.stage));const isFailed=t.type==='exception';return steps.map((step,index)=>{const started=addTaskMinutes(base,steps.slice(0,index).reduce((sum,item)=>sum+item.minutes,0));const ended=addTaskMinutes(started,step.minutes);const isCurrent=index===stageIndex;const isDone=index<stageIndex||(t.stage==='已完成'&&index<steps.length-1);const state=isDone?'done':isCurrent?(isFailed?'failed':'current'):'';let timeText='未开始';if(isDone)timeText=`开始：${formatTaskStageTime(started)} · 完成：${formatTaskStageTime(ended)} · 耗时：${step.minutes} 分钟`;if(isCurrent&&isFailed)timeText=`开始：${formatTaskStageTime(started)} · 结束：${formatTaskStageTime(ended)} · 处理失败`;else if(isCurrent&&!isFailed)timeText=`开始：${formatTaskStageTime(started)} · 已耗时：${step.minutes} 分钟`;return `<li class="${state}"><strong>${step.label}</strong><span>${step.desc}</span><small class="stage-time">${timeText}</small></li>`}).join('')}
function openDrawer(t){const uploaded=t.target||Math.max(42,Math.round(t.progress/100*80)),screened=Math.round(uploaded*.84),handled=Math.round(screened*.79),passed=Math.round(handled*.77),inbound=Math.min(passed,Math.round(passed*.97)),threeD=Math.round(inbound*.36);document.querySelector('#drawerTitle').textContent=t.name;document.querySelector('#drawerId').textContent=t.id;document.querySelector('#drawerBody').innerHTML=`<div class="detail-summary compact"><div><span>整体进度</span><strong>${t.progress}%</strong></div><div><span>负责人</span><strong style="font-size:14px">${t.owner}</strong></div></div><section class="detail-section"><h3>全流程统计</h3><div class="trace-stat-grid"><div><span>上传原图</span><b>${uploaded}</b></div><div><span>AI 初筛输出</span><b>${screened}</b></div><div><span>图片处理提交</span><b>${handled}</b></div><div><span>质检通过</span><b>${passed}</b></div><div><span>2D 已入库</span><b>${inbound}</b></div><div><span>已创建 3D 生成项</span><b>${threeD}</b></div></div><p class="trace-duration">开始：${t.time}　·　当前阶段已耗时：${t.progress>75?'1 小时 42 分':'26 分钟'}</p></section><section class="detail-section"><h3>任务流程</h3><ol class="timeline">${buildTaskTimeline(t)}</ol></section><section class="detail-section"><h3>当前统计</h3><div class="progress"><div class="progress-top"><strong>${t.meta}</strong><span>${t.progress}%</span></div><div class="progress-bar"><i style="width:${t.progress}%"></i></div></div></section>`;const nextAction=t.status==='待人工复核'?{label:'开始复核',href:`quality.html?tab=source&task=${t.id}`}:(t.status==='复核完成，待图生图配置'?{label:'进入图生图配置',href:`image-to-image.html?task=${t.id}&count=8`}:(t.status==='待人工质检'?{label:'开始质检',href:`quality.html?tab=generated&task=${t.id}`}:null));const drawerAction=document.querySelector('#drawerAction');drawerAction.hidden=!nextAction;drawerAction.textContent=nextAction?.label||'';drawerAction.dataset.href=nextAction?.href||'';drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');overlay.hidden=false}
function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');overlay.hidden=true}document.querySelector('#drawerClose').addEventListener('click',closeDrawer);document.querySelector('#drawerCancel').addEventListener('click',closeDrawer);overlay.addEventListener('click',closeDrawer);document.querySelector('#drawerAction').addEventListener('click',event=>{const href=event.currentTarget.dataset.href;if(href)location.href=href});
const modal=document.querySelector('#uploadModal'),uploadForm=document.querySelector('#uploadForm'),imageFolder=document.querySelector('#imageFolder'),uploadCount=document.querySelector('#uploadCount'),submitUpload=document.querySelector('#submitUpload');let selectedImages=[];
function closeUploadModal(){modal.hidden=true}
function resetUploadForm(){uploadForm.reset();selectedImages=[];uploadCount.className='upload-check-result empty';uploadCount.textContent='尚未选择文件夹';submitUpload.disabled=true}
document.querySelector('#uploadBtn').addEventListener('click',()=>{resetUploadForm();modal.hidden=false});document.querySelectorAll('.modal-close').forEach(x=>x.addEventListener('click',closeUploadModal));modal.addEventListener('click',e=>{if(e.target===modal)closeUploadModal()});
document.querySelector('#chooseFolder').addEventListener('click',()=>imageFolder.click());
function renderUploadCheck(total,success,failed,folderName){uploadCount.className=`upload-check-result ${success===0?'all-failed':failed===0?'all-success':'partial'}`;uploadCount.innerHTML=`<span>${folderName}：共 <b>${total}</b> 张</span><i>成功 <b>${success}</b> 张</i><em>失败 <b>${failed}</b> 张</em>${success===0?'<small>没有可上传图片，请更换或清理文件夹后重试</small>':failed>0?'<small>失败图片不会进入本次任务</small>':'<small>所有图片均可上传</small>'}`;submitUpload.disabled=success===0}
function isUsableImage(file){const valid=/\.(png|jpe?g|webp)$/i.test(file.name)&&file.size>0;if(!valid)return Promise.resolve(false);return new Promise(resolve=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{URL.revokeObjectURL(url);resolve(true)};image.onerror=()=>{URL.revokeObjectURL(url);resolve(false)};image.src=url})}
async function validateFolder(fileList){const files=Array.from(fileList);if(!files.length){resetUploadForm();return}submitUpload.disabled=true;uploadCount.className='upload-check-result checking';uploadCount.textContent=`正在检测 ${files.length} 张图片…`;const checks=await Promise.all(files.map(isUsableImage));selectedImages=files.filter((file,index)=>checks[index]);const failed=files.length-selectedImages.length,folderName=files[0].webkitRelativePath.split('/')[0]||'图片文件夹';renderUploadCheck(files.length,selectedImages.length,failed,folderName)}
imageFolder.addEventListener('change',()=>validateFolder(imageFolder.files));
uploadForm.addEventListener('submit',e=>{e.preventDefault();if(!uploadForm.reportValidity())return;if(!selectedImages.length){uploadCount.className='upload-check-result all-failed';uploadCount.textContent='没有可上传图片，请重新选择文件夹';return}const name=document.querySelector('#itemName').value.trim(),owner=document.querySelector('#taskOwner').value,note=document.querySelector('#taskRemark').value.trim(),total=selectedImages.length,task={id:`2D-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${String(127+tasks.length).padStart(5,'0')}`,name,note,category:'未分类',stage:'批量上传原图',status:'上传中',type:'running',progress:4,target:0,meta:`上传中 0 / ${total}`,owner,time:'刚刚'};tasks.unshift(task);closeUploadModal();syncStatusOptions();render();showToast('已创建上传任务，正在上传可用原图');setTimeout(()=>{task.stage='AI 初筛';task.status='排队中';task.type='neutral';task.progress=10;task.meta=`上传 ${total} / ${total} · 等待 AI 初筛`;syncStatusOptions();render()},1100);setTimeout(()=>{task.status='处理中';task.type='running';task.progress=18;task.meta=`上传 ${total} · 初筛中 0 / ${total}`;syncStatusOptions();render()},2200)});
document.querySelectorAll('.future').forEach(x=>x.addEventListener('click',()=>showToast(`${x.dataset.future}将在后续页面中完善`)));const toast=document.querySelector('#toast');let timer;function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2200)}listTimeFilter.addEventListener('change',render);document.querySelector('#openStats').addEventListener('click',()=>{updateStatsModal();statsModal.hidden=false});document.querySelectorAll('.stats-close').forEach(button=>button.addEventListener('click',()=>statsModal.hidden=true));statsModal.addEventListener('click',event=>{if(event.target===statsModal)statsModal.hidden=true});statsPeriodFilter.addEventListener('change',event=>{const isCustom=event.currentTarget.value==='custom';statsCustomRange.hidden=!isCustom;if(isCustom){statsPeriodStart.value='2026-09-01';statsPeriodEnd.value='2026-09-10'}updateStatsModal()});[statsPeriodStart,statsPeriodEnd].forEach(input=>input.addEventListener('change',()=>{if(statsPeriodFilter.value==='custom'&&statsPeriodStart.value&&statsPeriodEnd.value&&statsPeriodStart.value<=statsPeriodEnd.value)updateStatsModal()}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();modal.hidden=true}});syncStatusOptions();render();
