const generatedTasks=[
  {id:'2D-20260910-00126',name:'人体工学办公椅',owner:'陈建模',success:6,failed:2},
  {id:'2D-20260910-00123',name:'工业金属工具柜',owner:'王岩',success:2,failed:0}
];
const generatedItems=Array.from({length:8},(_,index)=>{const task=index<6?generatedTasks[0]:generatedTasks[1];return {id:index+1,taskId:task.id,name:task.name,owner:task.owner,status:'pending',sourceId:String(index+1).padStart(2,'0'),tone:['#e2edff','#e9f1e9','#f4e8d7','#e8e2f5','#e0eef0','#f3e2e5'][index%6]}});
const generatedGrid=document.querySelector('#generatedGrid'),generatedStatusFilter=document.querySelector('#generatedStatusFilter'),generatedSearch=document.querySelector('#generatedSearch'),generatedOwnerFilter=document.querySelector('#generatedOwnerFilter'),inboundModal=document.querySelector('#inboundModal');
let generatedSelected=new Set(),inboundTask=null;

function generatedStatusText(status){return({pending:'未处理',approved:'已通过',rejected:'已不通过'})[status]}
function generatedTaskItems(taskId){return generatedItems.filter(item=>item.taskId===taskId)}
function generatedStats(taskId){const items=generatedTaskItems(taskId);return {approved:items.filter(item=>item.status==='approved').length,rejected:items.filter(item=>item.status==='rejected').length,pending:items.filter(item=>item.status==='pending').length,selected:items.filter(item=>generatedSelected.has(item.id)).length}}
function filteredGeneratedItems(){const keyword=generatedSearch.value.trim().toLowerCase(),owner=generatedOwnerFilter.value;return generatedItems.filter(item=>(generatedStatusFilter.value==='all'||item.status===generatedStatusFilter.value)&&(!keyword||item.name.toLowerCase().includes(keyword))&&(owner==='all'||item.owner===owner))}
function generatedControls(task){const stats=generatedStats(task.id);if(!stats.pending)return '';return `<div class="task-review-controls"><span>已选 ${stats.selected} 张</span><button data-generated-select-all="${task.id}">全选</button><button data-generated-invert="${task.id}">反选</button><button data-generated-batch="rejected" data-generated-task="${task.id}" ${stats.selected?'':'disabled'}>批量不通过</button><button class="task-batch-approve" data-generated-batch="approved" data-generated-task="${task.id}" ${stats.selected?'':'disabled'}>批量通过</button></div>`}
function generatedAction(task){const stats=generatedStats(task.id);if(task.inbound==='done')return '<button class="ghost-btn task-action task-ended" disabled>已入库</button>';if(task.inbound==='processing')return '<button class="ghost-btn task-action" disabled>入库中</button>';if(task.ended)return '<button class="ghost-btn task-action task-ended" disabled>任务已结束</button>';if(stats.pending)return `<button class="ghost-btn task-action" disabled>仍有 ${stats.pending} 张未处理</button>`;if(stats.approved)return `<button class="primary-btn task-action" data-open-inbound="${task.id}">确认入库（已通过 ${stats.approved} 张）</button>`;return `<button class="ghost-btn task-action" data-generated-end="${task.id}">结束任务</button>`}
function generatedCard(item){return `<article class="review-card ${item.status}"><label class="review-select"><input type="checkbox" data-generated-select="${item.id}" ${generatedSelected.has(item.id)?'checked':''}><span></span></label><div class="image-swatch" style="--swatch:${item.tone}"><span>生成图 ${String(item.id).padStart(2,'0')}</span></div><div class="review-item-meta"><strong>原图 ID：${item.sourceId}</strong><span>GEN-${String(item.id).padStart(4,'0')}</span></div><div class="review-card-footer"><span class="review-status ${item.status}">${generatedStatusText(item.status)}</span><div class="review-card-actions">${item.status==='pending'?`<button data-generated-reject="${item.id}">不通过</button><button class="card-approve" data-generated-approve="${item.id}">通过</button>`:'<span class="handled-text">已处理</span>'}</div></div></article>`}
function updateGeneratedSummary(){const counts=generatedItems.reduce((result,item)=>({...result,[item.status]:result[item.status]+1}),{pending:0,approved:0,rejected:0});document.querySelector('#generatedApprovedCount').textContent=counts.approved;document.querySelector('#generatedRejectedCount').textContent=counts.rejected;document.querySelector('#generatedPendingCount').textContent=counts.pending;document.querySelector('#generatedResultCount').textContent=`共 ${filteredGeneratedItems().length} 张`}
function renderGenerated(){const visible=filteredGeneratedItems(),groups=generatedTasks.map(task=>({task,items:visible.filter(item=>item.taskId===task.id)})).filter(group=>group.items.length);generatedGrid.innerHTML=groups.map(({task,items})=>{const stats=generatedStats(task.id);return `<section class="task-review-group"><header class="task-review-header"><div><strong>${task.name}</strong><span>${task.id} · ${task.owner}</span></div>${generatedControls(task)}<div class="task-review-progress">图生图：成功 ${task.success} · 失败 ${task.failed}<br>已通过 ${stats.approved} · 已不通过 ${stats.rejected} · 未处理 ${stats.pending}</div>${generatedAction(task)}</header><div class="task-review-cards">${items.map(generatedCard).join('')}</div></section>`}).join('');bindGeneratedActions();updateGeneratedSummary()}
function setGeneratedStatus(ids,status){ids.forEach(id=>{const item=generatedItems.find(row=>row.id===id);if(item)item.status=status;generatedSelected.delete(id)});renderGenerated();toastMessage(status==='approved'?'生成图已通过质检':'生成图已标记为不通过')}
function openInbound(taskId){const task=generatedTasks.find(item=>item.id===taskId),stats=generatedStats(taskId);inboundTask=task;document.querySelector('#inboundName').textContent=task.name;document.querySelector('#inboundCount').textContent=`${stats.approved} 张`;inboundModal.hidden=false}
function bindGeneratedActions(){generatedGrid.querySelectorAll('[data-generated-select]').forEach(input=>input.addEventListener('change',()=>{input.checked?generatedSelected.add(Number(input.dataset.generatedSelect)):generatedSelected.delete(Number(input.dataset.generatedSelect));renderGenerated()}));generatedGrid.querySelectorAll('[data-generated-select-all]').forEach(button=>button.addEventListener('click',()=>{generatedTaskItems(button.dataset.generatedSelectAll).filter(item=>item.status==='pending').forEach(item=>generatedSelected.add(item.id));renderGenerated()}));generatedGrid.querySelectorAll('[data-generated-invert]').forEach(button=>button.addEventListener('click',()=>{generatedTaskItems(button.dataset.generatedInvert).filter(item=>item.status==='pending').forEach(item=>generatedSelected.has(item.id)?generatedSelected.delete(item.id):generatedSelected.add(item.id));renderGenerated()}));generatedGrid.querySelectorAll('[data-generated-approve]').forEach(button=>button.addEventListener('click',()=>setGeneratedStatus([Number(button.dataset.generatedApprove)],'approved')));generatedGrid.querySelectorAll('[data-generated-reject]').forEach(button=>button.addEventListener('click',()=>setGeneratedStatus([Number(button.dataset.generatedReject)],'rejected')));generatedGrid.querySelectorAll('[data-generated-batch]').forEach(button=>button.addEventListener('click',()=>setGeneratedStatus(generatedTaskItems(button.dataset.generatedTask).filter(item=>generatedSelected.has(item.id)&&item.status==='pending').map(item=>item.id),button.dataset.generatedBatch)));generatedGrid.querySelectorAll('[data-generated-end]').forEach(button=>button.addEventListener('click',()=>{const task=generatedTasks.find(item=>item.id===button.dataset.generatedEnd);task.ended=true;renderGenerated();toastMessage('该物品任务已结束')}));generatedGrid.querySelectorAll('[data-open-inbound]').forEach(button=>button.addEventListener('click',()=>openInbound(button.dataset.openInbound)))}
generatedStatusFilter.addEventListener('change',renderGenerated);generatedSearch.addEventListener('input',renderGenerated);generatedOwnerFilter.addEventListener('change',renderGenerated);document.querySelector('#generatedReset').addEventListener('click',()=>{generatedStatusFilter.value='all';generatedSearch.value='';generatedOwnerFilter.value='all';generatedSelected.clear();renderGenerated()});document.querySelectorAll('.inbound-close').forEach(button=>button.addEventListener('click',()=>inboundModal.hidden=true));inboundModal.addEventListener('click',event=>{if(event.target===inboundModal)inboundModal.hidden=true});document.querySelector('#inboundConfirm').addEventListener('click',()=>{if(!inboundTask)return;inboundTask.inbound='processing';inboundModal.hidden=true;renderGenerated();toastMessage('已提交入库，正在创建 2D Asset');setTimeout(()=>{inboundTask.inbound='done';renderGenerated();toastMessage('入库成功，已创建正式 2D Asset')},900)});renderGenerated();
