const assets=[
  {id:'2D-ASSET-20260910-000381',name:'人体工学办公椅',source:'2D-20260910-00126',note:'用于办公场景资产',owner:'陈建模',time:'今天 11:20',threeD:'not_started',tone:'#dfeafe'},
  {id:'2D-ASSET-20260910-000382',name:'人体工学办公椅',source:'2D-20260910-00126',note:'用于办公场景资产',owner:'陈建模',time:'今天 11:20',threeD:'not_started',tone:'#e9f1e9'},
  {id:'2D-ASSET-20260910-000383',name:'复古皮质行李箱',source:'2D-20260910-00124',note:'突出皮质纹理',owner:'陈建模',time:'今天 10:55',threeD:'generating',tone:'#f4e8d7'},
  {id:'2D-ASSET-20260909-000366',name:'陶瓷花瓶',source:'2D-20260909-00119',note:'',owner:'林嘉',time:'昨天 16:18',threeD:'completed',tone:'#e8e2f5'},
  {id:'2D-ASSET-20260909-000365',name:'原木圆形餐桌',source:'2D-20260909-00122',note:'餐桌素材补充批次',owner:'陈建模',time:'昨天 18:46',threeD:'failed',tone:'#e0eef0'}
];
const assetBody=document.querySelector('#assetBody'),assetSearch=document.querySelector('#assetSearch'),assetOwnerFilter=document.querySelector('#assetOwnerFilter'),asset3dFilter=document.querySelector('#asset3dFilter'),assetEmpty=document.querySelector('#assetEmpty'),assetCount=document.querySelector('#assetCount'),threeDModal=document.querySelector('#threeDModal'),assetToast=document.querySelector('#assetToast');let selectedAsset=null,toastTimer;
const threeDLabels={not_started:'未发起 3D',generating:'生成中',completed:'已完成',failed:'生成失败'};
function toast(message){assetToast.textContent=message;assetToast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>assetToast.classList.remove('show'),2000)}
function filteredAssets(){const keyword=assetSearch.value.trim().toLowerCase(),owner=assetOwnerFilter.value,status=asset3dFilter.value;return assets.filter(asset=>(!keyword||asset.name.toLowerCase().includes(keyword)||asset.id.toLowerCase().includes(keyword))&&(owner==='all'||asset.owner===owner)&&(status==='all'||asset.threeD===status))}
function action(asset){if(asset.threeD==='not_started')return `<button class="action-link" data-details="${asset.id}">详情</button><button class="action-link" data-start-3d="${asset.id}">发起 3D</button>`;if(asset.threeD==='failed')return `<button class="action-link" data-details="${asset.id}">详情</button><button class="action-link" data-start-3d="${asset.id}">重试 3D</button>`;return `<button class="action-link" data-details="${asset.id}">详情</button><button class="action-link" data-view-3d="${asset.id}">查看 3D 任务</button>`}
function renderAssets(){const rows=filteredAssets();assetBody.innerHTML=rows.map(asset=>`<tr><td><div class="asset-cell"><div class="asset-swatch" style="--asset-tone:${asset.tone}">2D</div><div class="task-name"><strong>${asset.name}</strong><code>${asset.id}</code></div></div></td><td><code class="source-id">${asset.source}</code></td><td><span class="task-note" title="${asset.note}">${asset.note||'—'}</span></td><td><div class="owner"><span class="mini-avatar">${asset.owner[0]}</span>${asset.owner}</div></td><td><span class="time">${asset.time}</span></td><td><span class="asset-status ${asset.threeD}">${threeDLabels[asset.threeD]}</span></td><td>${action(asset)}<button class="more-btn" aria-label="更多">•••</button></td></tr>`).join('');assetEmpty.classList.toggle('show',rows.length===0);assetCount.textContent=`共 ${rows.length} 条`;bindActions()}
function openThreeD(asset){selectedAsset=asset;document.querySelector('#threeDAssetName').textContent=asset.name;document.querySelector('#threeDAssetId').textContent=asset.id;document.querySelector('#threeDSwatch').style.setProperty('--asset-tone',asset.tone);threeDModal.hidden=false}
function bindActions(){assetBody.querySelectorAll('[data-start-3d]').forEach(button=>button.addEventListener('click',()=>openThreeD(assets.find(asset=>asset.id===button.dataset.start3d))));assetBody.querySelectorAll('[data-details]').forEach(button=>button.addEventListener('click',()=>toast('素材详情将在后续页面中展开')));assetBody.querySelectorAll('[data-view-3d]').forEach(button=>button.addEventListener('click',()=>toast('已跳转至 Gen2Sim 3D 任务')))}
assetSearch.addEventListener('input',renderAssets);assetOwnerFilter.addEventListener('change',renderAssets);asset3dFilter.addEventListener('change',renderAssets);document.querySelector('#assetReset').addEventListener('click',()=>{assetSearch.value='';assetOwnerFilter.value='all';asset3dFilter.value='all';renderAssets()});document.querySelectorAll('.three-d-close').forEach(button=>button.addEventListener('click',()=>threeDModal.hidden=true));threeDModal.addEventListener('click',event=>{if(event.target===threeDModal)threeDModal.hidden=true});document.querySelector('#threeDForm').addEventListener('submit',event=>{event.preventDefault();if(!selectedAsset)return;selectedAsset.threeD='generating';threeDModal.hidden=true;renderAssets();toast('3D 生成任务已创建，正在跳转 Gen2Sim')});renderAssets();
