const reviewTasks=[
  {id:'2D-20260910-00126',name:'人体工学办公椅',category:'家具',owner:'陈建模'},
  {id:'2D-20260910-00127',name:'现代玻璃花瓶',category:'家居用品',owner:'陈建模'},
  {id:'2D-20260910-00125',name:'北欧落地灯',category:'灯具',owner:'林嘉'},
  {id:'2D-20260910-00123',name:'工业金属工具柜',category:'工具设备',owner:'王岩'}
];
const reviewItems=Array.from({length:12},(_,index)=>{const task=reviewTasks[Math.floor(index/3)];return {id:index+1,taskId:task.id,name:task.name,category:task.category,owner:task.owner,status:'pending',tone:['#dfeafe','#e8f0e9','#f3e7d5','#e7e0f5','#dfecef','#f2e1e3'][index%6]}});
const reviewGrid=document.querySelector('#reviewGrid'),statusFilter=document.querySelector('#reviewStatusFilter'),searchInput=document.querySelector('#reviewSearch'),ownerFilter=document.querySelector('#reviewOwnerFilter'),toast=document.querySelector('#reviewToast');
let selected=new Set(),timer;

function toastMessage(message){toast.textContent=message;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),1800)}
function statusText(status){return({pending:'未处理',approved:'已通过',rejected:'已不通过'})[status]}
function filteredItems(){const keyword=searchInput?.value.trim().toLowerCase()||'',owner=ownerFilter?.value||'all';return reviewItems.filter(item=>(statusFilter.value==='all'||item.status===statusFilter.value)&&(!keyword||item.name.toLowerCase().includes(keyword))&&(owner==='all'||item.owner===owner))}
function taskItems(taskId){return reviewItems.filter(item=>item.taskId===taskId)}
function taskStats(taskId){const items=taskItems(taskId);return {approved:items.filter(item=>item.status==='approved').length,rejected:items.filter(item=>item.status==='rejected').length,pending:items.filter(item=>item.status==='pending').length,selected:items.filter(item=>selected.has(item.id)).length}}
function updateSummary(){const counts=reviewItems.reduce((result,item)=>({...result,[item.status]:result[item.status]+1}),{pending:0,approved:0,rejected:0});document.querySelector('#approvedCount').textContent=counts.approved;document.querySelector('#rejectedCount').textContent=counts.rejected;document.querySelector('#pendingCount').textContent=counts.pending;document.querySelector('#reviewResultCount').textContent=`共 ${filteredItems().length} 张`}
function taskAction(task){const stats=taskStats(task.id);if(task.ended)return '<button class="ghost-btn task-action task-ended" disabled>任务已结束</button>';if(stats.pending)return `<button class="ghost-btn task-action" disabled>仍有 ${stats.pending} 张未处理</button>`;if(stats.approved)return `<a class="primary-btn task-action" href="image-to-image.html?task=${task.id}&count=${stats.approved}">进入图生图配置（已通过 ${stats.approved} 张）</a>`;return `<button class="ghost-btn task-action" data-end-task="${task.id}">结束任务</button>`}
function taskControls(task){const stats=taskStats(task.id);if(!stats.pending)return '';return `<div class="task-review-controls"><span>已选 ${stats.selected} 张</span><button data-select-all="${task.id}">全选</button><button data-invert-selection="${task.id}">反选</button><button data-task-batch="rejected" data-task-id="${task.id}" ${stats.selected?'':'disabled'}>批量不通过</button><button class="task-batch-approve" data-task-batch="approved" data-task-id="${task.id}" ${stats.selected?'':'disabled'}>批量通过</button></div>`}
function card(item){return `<article class="review-card ${item.status}"><label class="review-select"><input type="checkbox" data-select="${item.id}" ${selected.has(item.id)?'checked':''}><span></span></label><div class="image-swatch" style="--swatch:${item.tone}"><span>原图 ${String(item.id).padStart(2,'0')}</span></div><div class="review-card-footer"><span class="review-status ${item.status}">${statusText(item.status)}</span><div class="review-card-actions">${item.status==='pending'?`<button data-reject="${item.id}">不通过</button><button class="card-approve" data-approve="${item.id}">通过</button>`:'<span class="handled-text">已处理</span>'}</div></div></article>`}
function renderReview(){const visible=filteredItems(),groups=reviewTasks.map(task=>({task,items:visible.filter(item=>item.taskId===task.id)})).filter(group=>group.items.length);reviewGrid.innerHTML=groups.map(({task,items})=>{const stats=taskStats(task.id);return `<section class="task-review-group"><header class="task-review-header"><div><strong>${task.name}</strong><span>${task.id} · ${task.owner}</span></div>${taskControls(task)}<div class="task-review-progress">已通过 ${stats.approved} · 已不通过 ${stats.rejected} · 未处理 ${stats.pending}</div>${taskAction(task)}</header><div class="task-review-cards">${items.map(card).join('')}</div></section>`}).join('');bindReviewActions();updateSummary()}
function bindReviewActions(){reviewGrid.querySelectorAll('[data-select]').forEach(input=>input.addEventListener('change',()=>{input.checked?selected.add(Number(input.dataset.select)):selected.delete(Number(input.dataset.select));renderReview()}));reviewGrid.querySelectorAll('[data-approve]').forEach(button=>button.addEventListener('click',()=>applyStatus([Number(button.dataset.approve)],'approved')));reviewGrid.querySelectorAll('[data-reject]').forEach(button=>button.addEventListener('click',()=>applyStatus([Number(button.dataset.reject)],'rejected')));reviewGrid.querySelectorAll('[data-select-all]').forEach(button=>button.addEventListener('click',()=>{taskItems(button.dataset.selectAll).filter(item=>item.status==='pending').forEach(item=>selected.add(item.id));renderReview()}));reviewGrid.querySelectorAll('[data-invert-selection]').forEach(button=>button.addEventListener('click',()=>{taskItems(button.dataset.invertSelection).filter(item=>item.status==='pending').forEach(item=>selected.has(item.id)?selected.delete(item.id):selected.add(item.id));renderReview()}));reviewGrid.querySelectorAll('[data-task-batch]').forEach(button=>button.addEventListener('click',()=>{const ids=taskItems(button.dataset.taskId).filter(item=>selected.has(item.id)&&item.status==='pending').map(item=>item.id);applyStatus(ids,button.dataset.taskBatch)}));reviewGrid.querySelectorAll('[data-end-task]').forEach(button=>button.addEventListener('click',()=>{const task=reviewTasks.find(item=>item.id===button.dataset.endTask);if(task){task.ended=true;renderReview();toastMessage('该物品任务已结束')}}))}
function applyStatus(ids,status){ids.forEach(id=>{const item=reviewItems.find(row=>row.id===id);if(item)item.status=status;selected.delete(id)});renderReview();toastMessage(status==='approved'?'图片已通过复核':'图片已标记为不通过')}
statusFilter.addEventListener('change',renderReview);searchInput?.addEventListener('input',renderReview);ownerFilter?.addEventListener('change',renderReview);document.querySelector('#reviewReset').addEventListener('click',()=>{statusFilter.value='all';if(searchInput)searchInput.value='';if(ownerFilter)ownerFilter.value='all';selected.clear();renderReview()});renderReview();
